environment: development
replicaCount: 1

image:
  repository: your-registry.io/tosyeno-web-app
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

ingress:
  enabled: true
  hosts:
    - host: dev.app.example.com
      paths:
        - path: /
          pathType: Prefix
